ALTER TYPE "TrackId" ADD VALUE IF NOT EXISTS 'tom_low';
ALTER TYPE "TrackId" ADD VALUE IF NOT EXISTS 'tom_high';
ALTER TYPE "TrackId" ADD VALUE IF NOT EXISTS 'rim';
ALTER TYPE "TrackId" ADD VALUE IF NOT EXISTS 'keyboard';
